### ISSUE TITLE
Unable to change the navigation of the "Help" tab. 

### ISSUE THREAD

**Issue by radithottoli** [genepi/imputationserver#50]
Hi, 

I am trying to change the navigation of the "Help" to our own documentation created using readthedocs but I am unable to do so. 

I have tried changing the navigation in the **settings.yaml** file in config but I can't see the change in action. 

**This is the current one**

```
navigation:
  - id: help
    name: Help
    link: http://docs.cloudgene.io
```

**This is the change I am trying to implement**

```
navigation:
  - id: help
    name: Help
    link: https://qatarimputationserver.readthedocs.io/en/latest/
```
