### ISSUE TITLE
Importing new panel imputation fails on QC

### ISSUE THREAD

**Issue by shakeeljessa** [genepi/imputationserver#74]
Hi! We are attempting to perform imputation using a Haplotype Reference Consortium panel (with GRCh37/hg19 data). We have installed the panel and are able to see it as an option when running a job. However, the imputation fails for some reason when generating the QC report. 

Here are our logs from the job:
```
job.txt:

22/01/18 13:55:24 Executing Job installation....
22/01/18 13:55:24   Preparing Application 'Genotype Imputation (Minimac4)'...
22/01/18 13:55:24   Application 'Genotype Imputation (Minimac4)'is already installed.
22/01/18 13:55:24   Preparing Application 'Haplotype Reference Consortium Panel'...
22/01/18 13:55:24   Application 'Haplotype Reference Consortium Panel'is already installed.
22/01/18 13:55:24 Executing Job setups....
22/01/18 13:55:24 Planner: WDL evaluated.
22/01/18 13:55:24 Planner: DAG created.
22/01/18 13:55:24   Nodes: 3
22/01/18 13:55:24     Input Validation
22/01/18 13:55:24       Inputs: 
22/01/18 13:55:24       Outputs: 
22/01/18 13:55:24     Quality Control
22/01/18 13:55:24       Inputs: 
22/01/18 13:55:24       Outputs: mafFile chunkFileDir statisticDir 
22/01/18 13:55:24     Quality Control (Report)
22/01/18 13:55:24       Inputs: mafFile r2Filter myseparator check1 check2 
22/01/18 13:55:24       Outputs: qcreport 
22/01/18 13:55:24   Dependencies: 2
22/01/18 13:55:24     Input Validation->Quality Control
22/01/18 13:55:24     Quality Control->Quality Control (Report)
22/01/18 13:55:24 Executor: execute DAG...
22/01/18 13:55:24 ------------------------------------------------------
22/01/18 13:55:24 Input Validation
22/01/18 13:55:24 ------------------------------------------------------
22/01/18 13:55:24 Versions:
22/01/18 13:55:24   Pipeline: michigan-imputationserver-1.5.7
22/01/18 13:55:24   Imputation-Engine: minimac4-1.0.2
22/01/18 13:55:24   Phasing-Engine: eagle-2.4
22/01/18 13:55:24 Configuration file '/data/apps/imputationserver/1.5.7/job.config' not available. Use default values.
22/01/18 13:55:24   Input Validation [0 sec]
22/01/18 13:55:24 ------------------------------------------------------
22/01/18 13:55:24 Quality Control
22/01/18 13:55:24 ------------------------------------------------------
22/01/18 13:55:24 Configuration file '/data/apps/imputationserver/1.5.7/job.config' not available. Use default values.
22/01/18 13:55:24 Reference Panel Ranges: genome-wide
22/01/18 13:55:25   Quality Control [0 sec]
22/01/18 13:55:25   Exporting parameter statisticDir...
22/01/18 13:55:25   Added 3 downloads.
22/01/18 13:55:25   Added 0 custom downloads.
22/01/18 13:55:25 ------------------------------------------------------
22/01/18 13:55:25 Quality Control (Report)
22/01/18 13:55:25 ------------------------------------------------------
22/01/18 13:55:25 Running script /data/apps/imputationserver/1.5.7/qc-report.Rmd...
22/01/18 13:55:25 Working Directory: /data/apps/imputationserver/1.5.7
22/01/18 13:55:25 Output: /data/jobs/job-20220118-135524-523/qcreport/qcreport.html
22/01/18 13:55:25 Parameters:
22/01/18 13:55:25   /data/jobs/job-20220118-135524-523/temp/mafFile/mafFile
22/01/18 13:55:25 Creating RMarkdown report from /data/apps/imputationserver/1.5.7/qc-report.Rmd...
22/01/18 13:55:30   Quality Control (Report) [ERROR]
22/01/18 13:55:30   Exporting parameter qcreport...
22/01/18 13:55:30   Added 0 downloads.
22/01/18 13:55:30   Added 0 custom downloads.
22/01/18 13:55:30 Executing onFailure... 
22/01/18 13:55:30 ------------------------------------------------------
22/01/18 13:55:30 Send Notification on Failure
22/01/18 13:55:30 ------------------------------------------------------
22/01/18 13:55:30 Configuration file '/data/apps/imputationserver/1.5.7/job.config' not available. Use default values.
22/01/18 13:55:30   Send Notification on Failure [ERROR]
22/01/18 13:55:30 onFailure execution failed.
22/01/18 13:55:30 Job execution failed: Job Execution failed.
22/01/18 13:55:30 Cleaning up...
22/01/18 13:55:30 Cleaning up uploaded local files...
22/01/18 13:55:30 Cleaning up temporary local files...
22/01/18 13:55:30 Cleaning up temporary hdfs files...
22/01/18 13:55:30 Cleaning up hdfs files...
22/01/18 13:55:30 Cleanup successful.


std.out:

Export parameter 'statisticDir'...


processing file: qc-report.Rmd
Quitting from lines 5-16 (qc-report.Rmd) 
Error in read.table(input, header = FALSE, sep = "\t") : 
  no lines available in input
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> read.table
Execution halted


  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |..........                                                            |  14%
  ordinary text without R code


  |                                                                            
  |....................                                                  |  29%
label: unnamed-chunk-1 (with options) 
List of 1
 $ echo: logi FALSE



Export parameter 'qcreport'...
No action required. Email notification has been disabled in job.config
```

And here is our `yaml` file if that is useful:
```
name: Haplotype Reference Consortium Panel
description: Panel built from hrc-EGAD00001002729
category: RefPanel
version: 1.1

properties:
  id: HRC
  hdfs: ${app_hdfs_folder}/m3vcfs/HRC.r1-1.EGA.GRCh37.chr$chr.m3vcf.gz
  legend: ${app_local_folder}/legend/HRC.r1-1.EGA.GRCh37.chr$chr.legend.gz
  mapEagle: ${app_hdfs_folder}/map/genetic_map_hg19_withX.txt.gz
  refEagle: ${app_hdfs_folder}/bcfs/HRC.r1-1.EGA.GRCh37.chr$chr.bcf
  build: hg19
  samples:
    all: 27165
    mixed: -1
  populations:
    all: ALL
    mixed: Other/Mixed

installation:

  - import:
      source: ${app_local_folder}/bcfs
      target: ${app_hdfs_folder}/bcfs

  - import:
      source: ${app_local_folder}/m3vcfs
      target: ${app_hdfs_folder}/m3vcfs

  - import:
      source: ${app_local_folder}/map
      target: ${app_hdfs_folder}/map


```
